#!/bin/sh
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xepmuytrgi:c --reverse_order > ../test_output/reverse_order/test_run0.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xepgmuytri:c --reverse_order > ../test_output/reverse_order/test_run1.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xgepmuytri:c --reverse_order > ../test_output/reverse_order/test_run2.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gxepmuytri:c --reverse_order > ../test_output/reverse_order/test_run3.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xepmuytrig:c --reverse_order > ../test_output/reverse_order/test_run4.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xepimuytrg:c --reverse_order > ../test_output/reverse_order/test_run5.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xiepmuytrg:c --reverse_order > ../test_output/reverse_order/test_run6.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xepgimuytr:c --reverse_order > ../test_output/reverse_order/test_run7.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xgepimuytr:c --reverse_order > ../test_output/reverse_order/test_run8.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gxepimuytr:c --reverse_order > ../test_output/reverse_order/test_run9.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xepigmuytr:c --reverse_order > ../test_output/reverse_order/test_run10.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xiepgmuytr:c --reverse_order > ../test_output/reverse_order/test_run11.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cgxmuytri:ep --reverse_order > ../test_output/reverse_order/test_run12.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gcxmuytri:ep --reverse_order > ../test_output/reverse_order/test_run13.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cxmuytrig:ep --reverse_order > ../test_output/reverse_order/test_run14.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cximuytrg:ep --reverse_order > ../test_output/reverse_order/test_run15.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cixmuytrg:ep --reverse_order > ../test_output/reverse_order/test_run16.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cxgimuytr:ep --reverse_order > ../test_output/reverse_order/test_run17.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cgximuytr:ep --reverse_order > ../test_output/reverse_order/test_run18.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gcximuytr:ep --reverse_order > ../test_output/reverse_order/test_run19.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cxigmuytr:ep --reverse_order > ../test_output/reverse_order/test_run20.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cixgmuytr:ep --reverse_order > ../test_output/reverse_order/test_run21.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cgixmuytr:ep --reverse_order > ../test_output/reverse_order/test_run22.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gcixmuytr:ep --reverse_order > ../test_output/reverse_order/test_run23.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cigxmuytr:ep --reverse_order > ../test_output/reverse_order/test_run24.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xmuytrgi:epc --reverse_order > ../test_output/reverse_order/test_run25.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xgmuytri:epc --reverse_order > ../test_output/reverse_order/test_run26.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gxmuytri:cep --reverse_order > ../test_output/reverse_order/test_run27.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cepxgi:muytr --reverse_order > ../test_output/reverse_order/test_run28.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gxmuytri:epc --reverse_order > ../test_output/reverse_order/test_run29.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cepgxi:muytr --reverse_order > ../test_output/reverse_order/test_run30.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cgepxi:muytr --reverse_order > ../test_output/reverse_order/test_run31.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gcepxi:muytr --reverse_order > ../test_output/reverse_order/test_run32.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cepxig:muytr --reverse_order > ../test_output/reverse_order/test_run33.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cepixg:muytr --reverse_order > ../test_output/reverse_order/test_run34.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order ciepxg:muytr --reverse_order > ../test_output/reverse_order/test_run35.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xmuytrig:epc --reverse_order > ../test_output/reverse_order/test_run36.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cepgix:muytr --reverse_order > ../test_output/reverse_order/test_run37.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cgepix:muytr --reverse_order > ../test_output/reverse_order/test_run38.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gcepix:muytr --reverse_order > ../test_output/reverse_order/test_run39.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cepigx:muytr --reverse_order > ../test_output/reverse_order/test_run40.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order ciepgx:muytr --reverse_order > ../test_output/reverse_order/test_run41.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cgiepx:muytr --reverse_order > ../test_output/reverse_order/test_run42.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gciepx:muytr --reverse_order > ../test_output/reverse_order/test_run43.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order ximuytrg:epc --reverse_order > ../test_output/reverse_order/test_run44.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order cigepx:muytr --reverse_order > ../test_output/reverse_order/test_run45.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xgimuytr:epc --reverse_order > ../test_output/reverse_order/test_run46.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gximuytr:cep --reverse_order > ../test_output/reverse_order/test_run47.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order gximuytr:epc --reverse_order > ../test_output/reverse_order/test_run48.txt
timeout 80s ../main --sas_file output.sas --build_bdd --timesteps 11 --build_order xigmuytr:epc --reverse_order > ../test_output/reverse_order/test_run49.txt
